
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-resize
  namespace: monitoring
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate 
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-data-pv
  namespace: monitoring
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: local 
  volumeMode: Filesystem
  local:
      path: /var/lib/influxdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-node1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: monitoring
spec:
  imagePullSecrets:
  - name: dockerhub-image-pull-secret-ankur
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: influxdb
        image: influxdb:latest
        ports:
        - containerPort: 8086
        volumeMounts:
        - name: influxdb-storage
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-storage
        persistentVolumeClaim:
          claimName: influxdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring
spec:
  type: NodePort
  externalIPs:
    - 172.16.222.61 
  selector:
    app: influxdb
  ports:
    - name: influxdb-port
      port: 8086
      targetPort: 8086
---
